### ISSUE TITLE
Connecting to the des-mpp system

### ISSUE THREAD

**Issue by joezuntz** [Samreay/ChainConsumer#10]
We would like to connect to the DES multiprobe pipeline system.

**Comment by joezuntz** [comment]
link: https://bitbucket.org/timeifler/des-mpp

**Comment by Samreay** [comment]
Bitbucket account is samreay

**Comment by Samreay** [comment]
Hi Joe, try updating to ChainConsumer 0.15.1, it should have AIC, BIC and DIC all in there. Example included at https://samreay.github.io/ChainConsumer/examples/plot_model_selection.html

**Comment by Samreay** [comment]
Hey @joezuntz, wondering if theres been any movement on this or if you need anything else on my end.
