### ISSUE TITLE
Plot truth in marginal distributions

### ISSUE THREAD

**Issue by renecotyfanboy** [Samreay/ChainConsumer#107]
Hi @Samreay 
I noticed that when adding a truth to a consumer, it does not display in the marginal distributions. I didn't find documentation about how to trigger this behaviour in 1.0. In the linked example, you can see there is a very thin, dotted line in the upper left marginal, right on top of the axe edge, which might signal this is buggy 

![394251192_301917602629873_275678884231070409_n](https://github.com/Samreay/ChainConsumer/assets/49200287/7380e1b0-dde1-4473-8247-5eb2810f885c)

**Comment by Samreay** [comment]
I wonder if this is a fun x/y axis swap!

**Comment by Samreay** [comment]
Will have this tagged and out on pypi in about 10 minutes
