### ISSUE TITLE
Walks with multiple chains

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#12]
Hi Sam,

Really nice package! 

I was hoping to plot walks with multiple chains, but it is not currently possible. I would think this would be easy enough -- the way I usually do it is to plot each chain with the same colour and a pretty low alpha. The resulting plot is "messy", but shows pretty clearly if there are any chains doing strange things compared to the rest.

What do you think?

**Comment by Samreay** [comment]
Yeah that seems agreeable. Give me a few minutes

**Comment by Samreay** [comment]
Commit 812190b should address this. Just waiting on tests, and Ill push out a new version.

**Comment by Samreay** [comment]
Tests passed, ChainConsumer released v0.15.3. See https://samreay.github.io/ChainConsumer/examples/plot_walk.html for multi-chain example. Thanks Steven!

**Comment by steven-murray** [comment]
Wow, that was fast! Thanks. I'll test it out.

________________________________
