### ISSUE TITLE
Chain straight from dict / chain from numpyro with only certain fields

### ISSUE THREAD

**Issue by benjaminpope** [Samreay/ChainConsumer#121]
Hi Sam,

Great that you have a `from_numpyro` method in `Chain` - very helpful. One thing that is common though is to have numpyro track some parameters as `Deterministic` - for example, saving model samples at the time they are calculated, or precalculating posterior predictive draws for plotting ([egs](https://dfm.io/posts/intro-to-numpyro/)). These will in general have a different shape to the other samples of scalar parameters.

While I understand that it is straightforward to pass it into pandas and make a DataFrame, this isn't very elegant. 

It would be convenient to be able to just pass a dict without `pd` wrapping, or to call `from_numpyro` with keys to use (or indeed keys to drop and others to be used).

Cheers,

Ben

**Comment by Samreay** [comment]
Sounds reasonable, for someone that's never used mumpyro, do you have some examples of this or how you'd modify the from_numpyro function to include deterministic samples?

**Comment by renecotyfanboy** [comment]
This is a good idea, I would require this kind of feature for my project too, I'll implement this asap

**Comment by renecotyfanboy** [comment]
I have open a PR where you can specify arguments to keep or discard using a new parameter (for the Chain.from_arviz or Chain.from_numpyro constructors). I'll wait the review from Sam before merging it, but in the meantime you can try it using : 

```
pip install git+https://github.com/Samreay/ChainConsumer.git@refs/pull/122/merge
```

and give me your feedback ! To use it, simply pass a list of string : 

`chain = Chain.from_numpyro(numpyro_mcmc, "numpyro", var_names=["mu", "sigma"])` to keep only mu and sigma parameters 
`chain = Chain.from_numpyro(numpyro_mcmc, "numpyro", var_names=["~mu", "~sigma"])` to keep everything but mu and sigma parameters

**Comment by Samreay** [comment]
I'll try and get in this asap if we get discharged tomorrow, otherwise
might be a few days. Thanks for doing the hard part, Simon!

**Comment by Samreay** [comment]
Hopefully the `var_names` kwarg in 1.1.0 does what you'd like. Thanks @renecotyfanboy and @benjaminpope :)

**Comment by benjaminpope** [comment]
Hero - thanks mate!
