### ISSUE TITLE
[Bug] Wrong type returned by `get_bins`

### ISSUE THREAD

**Issue by snwnde** [Samreay/ChainConsumer#125]
https://github.com/Samreay/ChainConsumer/blob/f461e0204139481f0a0c57c3a495785eb9f54199/src/chainconsumer/helpers.py#L42-L46

`np.floor` does not return a variable of `int` type. This creates problems for `get_smoothed_bins` when this value is returned by `get_bins`.

## Example
```python
df = pd.DataFrame(np.random.randn(10_000_000, 3), columns=["a", "b", "c"]

c = ChainConsumer()
c.add_chain(Chain(samples=df, name="test"))
c.plotter.plot()
```

**Comment by Samreay** [comment]
Thanks mate, good catch!
