### ISSUE TITLE
remove_chain method

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#13]
Hi again,

since you're so fast, I thought I'd ask another favour.  For what I'm doing, I'm using CC to do some convergence tests on a series of chains, and if they fail, I just want to skip that chain. The best way to do this, I think, is to have a remove_chain() method (or even just a remove_last_chain method) which undoes the add_chain() method. I've hacked one myself, but probably missing something important...

```python
def remove_last_chain(cc):
    del cc._chains[-1]
    del cc._names[-1]
    del cc._walkers[-1]
    del cc._posteriors[-1]
    del cc._weights[-1]
    del cc._parameters[-1]
    del cc._num_data[-1]
    del cc._num_free[-1]
```

**Comment by Samreay** [comment]
Now in v0.15.4. Documentation will be online in a couple of minutes

**Comment by steven-murray** [comment]
sweet. Clearly better than my version :)
