### ISSUE TITLE
Update CI and package management

### ISSUE THREAD

**Issue by renecotyfanboy** [Samreay/ChainConsumer#137]
Hi @Samreay, I hope your parental leave is going well :) 
I've just updated some dependencies, and I think it would be good to clear a bit the package management for chainconsumer. We have 3 files here to define the dependencies, while the pyproject.toml could unify everything. 
Also, it might be a good idea to add a Github action to deploy CC to pypi when new tags are released, it could smooth a bit the deployment of new versions.
WDYT ?

**Comment by renecotyfanboy** [comment]
@Samreay repinging about this, it would be super helpful to defer the package publication to a GitHub action. I would suggest to use `poetry` or even the newly release [`rye`](https://github.com/astral-sh/rye) if you feel adventurous

**Comment by Samreay** [comment]
Ah apologies, didn't even see this. What three files are you referring to by the way? The repo already uses poetry for dependency management, so the pyproject.toml should be the one stop shop.

Re automating deployments, the current github action automates a Github release to a pypi push, so the process right now is tag, flag that tag as a release, and you're done. We could assume all tags are releases, or moreso try to automate "tag following specific regex automatically becomes a release", if that's what you're suggesting?

**Comment by renecotyfanboy** [comment]
Wow, sorry everything's already in place, I must have been exhausted when I wrote this issue lmao. 

So if needed, I can release a new version with a new tag, and it will be deployed to pypi right?

**Comment by renecotyfanboy** [comment]
Nice ! TY and sorry for the extra noise
