### ISSUE TITLE
Covariance matrix

### ISSUE THREAD

**Issue by dparkins** [Samreay/ChainConsumer#14]
Can chain consumer output the correlation/covariance matrix between the parameters? Or flag the most correlated combination?

**Comment by Samreay** [comment]
Hmm, no it can't.... yet. I'll have a look into it now!

**Comment by Samreay** [comment]
Hi David,

Update to v0.15.7 and see these methods:

https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.ChainConsumer.get_correlations

https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.ChainConsumer.get_correlation_table

Cheers

**Comment by Samreay** [comment]
(Also realise I coded up a correlation matrix, but not a covariance matrix. Did you want covariance specifically?)

**Comment by dparkins** [comment]
Both are useful (and provided by GetDist)

**Comment by Samreay** [comment]
v0.16.0 now has covariance matrix stuff as well. Enjoy.
