### ISSUE TITLE
numpy 1.2 requirement in the wheel file

### ISSUE THREAD

**Issue by segasai** [Samreay/ChainConsumer#142]
Hi, 

I've been trying to understand why numpy 1.26 is being installed on my machine while pip installing some packages. 
And I've traced it to chainconsumer I believe. 

For some reason the wheel file ( from pypi) has this: 
Requires-Python: >=3.10,<3.13
Requires-Dist: matplotlib (>=3.6.0,<4.0.0)
Requires-Dist: numpy (>=1.23.0,<2.0.0)

While the pyproject.tom has this line:
numpy = "^1.23.0"

Actually didn't know, but apparently this corresponds to numpy (>=1.23.0,<2.0.0)

Is this actually intended ? 

Because I ran chainconsumer tests and they all pass fine with numpy 2.1... 

Thanks

**Comment by Samreay** [comment]
Good shout, I'll update the dependency to be >=1.23.0

**Comment by Samreay** [comment]
ChainConsumer 1.1.3 is now out and should resolve this problem. Thanks for raising the issue :)
