### ISSUE TITLE
tick_font_size not working

### ISSUE THREAD

**Issue by caitlinadams** [Samreay/ChainConsumer#16]
I find that changing this option does not actually change the font size on the figure. The label size option is responding correctly.

`import numpy as np
from numpy.random import normal, multivariate_normal
from chainconsumer import ChainConsumer

np.random.seed(0)
data = multivariate_normal([0, 1, 2], np.eye(3) + 0.2, size=100000)
c = ChainConsumer()
c.add_chain(data, parameters=["$x$", "$y^2$", r"$\Omega_\beta$"])
c.configure(diagonal_tick_labels=False, tick_font_size=2, label_font_size=16, max_ticks=4)
fig = c.plot(figsize="column")`

and 

`import numpy as np
from numpy.random import normal, multivariate_normal
from chainconsumer import ChainConsumer

np.random.seed(0)
data = multivariate_normal([0, 1, 2], np.eye(3) + 0.2, size=100000)
c = ChainConsumer()
c.add_chain(data, parameters=["$x$", "$y^2$", r"$\Omega_\beta$"])
c.configure(diagonal_tick_labels=False, tick_font_size=10, label_font_size=16, max_ticks=4)
fig = c.plot(figsize="column")`

produce the same figure.

**Comment by Samreay** [comment]
This makes me sad. Will look into it now.

**Comment by caitlinadams** [comment]
Thanks Sam! Sorry I made you sad!

**Comment by Samreay** [comment]
Try updating now :)

**Comment by caitlinadams** [comment]
Looks great! Thanks for doing that!
