### ISSUE TITLE
trying to use \mathrm in labels but failed

### ISSUE THREAD

**Issue by yangcht** [Samreay/ChainConsumer#17]
Hi, I was trying to put labels on each histogram,  the label is something like x_\mathrm{y}. Each time I got an error says latex can not process x_\\\mathrm_{y}. Apparently, it adds extra "//" there. Could you kindly fix this?

**Comment by Samreay** [comment]
Hi Chentao,

I'm unable to reproduce this error. The double slash is not ChainConsumer, but how python handles displaying the backlash character to indicate it is not an escape character. Are you sure you have constructed the label string correctly? Here is an example that works for me


```
import numpy as np
from chainconsumer import ChainConsumer

c = ChainConsumer()
c.add_chain(np.random.normal(size=100000), parameters=[r"$x_\mathrm{y}$"])
c.plot(figsize=2.0)
```

And that produces this image:

￼
![sssss](https://cloud.githubusercontent.com/assets/6748505/24387545/18e9bf42-13b9-11e7-9de9-0615af4778b7.png)

**Comment by yangcht** [comment]
Sorry, I have checked again my code, it was my mistake. Thanks for the prompt anwser!

**Comment by Samreay** [comment]
No worries mate
