### ISSUE TITLE
shading.

### ISSUE THREAD

**Issue by grburgess** [Samreay/ChainConsumer#18]
For some reason, the joint plots stopped shading the contours:

```
import numpy as np
from numpy.random import normal, multivariate_normal
from chainconsumer import ChainConsumer



np.random.seed(0)
cov = normal(size=(3, 3))
cov2 = normal(size=(4, 4))
data = multivariate_normal(normal(size=3), 0.5 * (cov + cov.T), size=100000)
data2 = multivariate_normal(normal(size=4), 0.5 * (cov2 + cov2.T), size=100000)

c = ChainConsumer()
c.add_chain(data, parameters=["$x$", "$y$", r"$\alpha$"])
c.add_chain(data2, parameters=["$x$", "$y$", r"$\alpha$", r"$\gamma$"])
fig = c.plot()
```
Is it something in the code?

![unknown-2](https://cloud.githubusercontent.com/assets/6764007/24696148/bf35534a-19e8-11e7-850b-836449448ef4.png)

**Comment by Samreay** [comment]
Hmm, there shouldn't be anything in the code that is doing stopping shading
for only two contours.

All the plots shown in the examples are automatically recreated with the
latest version of ChainConsumer on every git commit, and I can see that
example is shaded.

Is this with the latest version of ChainConsumer?

On Wed, Apr 5, 2017 at 6:15 PM, J. Michael Burgess <notifications@github.com

**Comment by grburgess** [comment]
Yup. I reinstalled to see. I thought it was very strange. I cleared my matplotlibrc just to be sure.
I even trade shade=True. It works on single fits though..

**Comment by Samreay** [comment]
That's super odd then! I'm not sure how to reproduce the bug, is it possible you can check to whether its something weird with ChainConsumer (and its not shading for some reason) or an oddity with matplotlib.

If you add two print statements to the example code, do they show that both chains will be shaded, and with shade_alpha set as 0.707?

```
import numpy as np
from numpy.random import normal, multivariate_normal
from chainconsumer import ChainConsumer



np.random.seed(0)
cov = normal(size=(3, 3))
cov2 = normal(size=(4, 4))
data = multivariate_normal(normal(size=3), 0.5 * (cov + cov.T), size=100000)
data2 = multivariate_normal(normal(size=4), 0.5 * (cov2 + cov2.T), size=100000)

c = ChainConsumer()
c.add_chain(data, parameters=["$x$", "$y$", r"$\alpha$"])
c.add_chain(data2, parameters=["$x$", "$y$", r"$\alpha$", r"$\gamma$"])
fig = c.plot()

print(c.config["shade"])
print(c.config["shade_alpha"])
```

Should give

```
[True, True]
[0.70710678118654757, 0.70710678118654757]
```

If it does not, this one must be on me somehow, if it does spit that out, can you confirm if line 1807 in `chain.py` gets executed? (https://github.com/Samreay/ChainConsumer/blob/master/chainconsumer/chain.py#L1807)

**Comment by grburgess** [comment]
Aha:

[True, True]
[0.0, 0.0]

**Comment by grburgess** [comment]
# Modify shade alpha based on how many chains we have
        if shade_alpha is None:
            if num_chains == 1:
                shade_alpha = 1.0
            else:
                shade_alpha = np.sqrt(1 / num_chains)

**Comment by grburgess** [comment]
Looks like you are doing int division

**Comment by grburgess** [comment]
This fixes it:

```
 # Modify shade alpha based on how many chains we have
        if shade_alpha is None:
            if num_chains == 1:
                shade_alpha = 1.0
            else:
                shade_alpha = np.sqrt(1. / float(num_chains))
```

**Comment by Samreay** [comment]
Ah, this is what happens when I work in python 3, I thought I had caught all of those, here's hoping thats the last!

Ill add a unit test for this explicitly and close it off. Cheers!

**Comment by grburgess** [comment]
Thanks!

**Comment by Samreay** [comment]
[Travis build passed](https://travis-ci.org/Samreay/ChainConsumer/builds/218799040), version 0.16.3 released, please update to be rid of that pesky problem! Apologies for the inconvenience mate.

**Comment by grburgess** [comment]
Danke. I've been thinking to contribute a bit and maybe break the code up into classes?

**Comment by Samreay** [comment]
Yeah I've been considering that for a while as well. Initially it was fine, but after people asked for convergence diagnostics, and model comparison tests, and all of that, its grown to a point where it's justified.

Was worried about making it difficult to use (god knows any API changes will have a bucket of issue's raised over it), but have resolved that I will split it up the next time someone asks for something new.

Was going to make it hierarchical so the API changes are more intuitive. So something like:

```
c = ChainConsumer()
c.add_chain(data)

c.configure(blah)

c.diagnostics.gelman_rubin()

c.compare.get_bic()

c.plotter.plot()
```

or something along those lines. Would that agree with your thinking or is there something more elegant I have overlooked?


If not, it would only take an few minutes or so and would be good be procrasticoding, so happy to do that myself when needed

**Comment by grburgess** [comment]
I think the API is pretty nice as it is. I’ve got a little interface into our code. 


Just more that the chain.py is rather long and could be perhaps broken up so that it is easier to contribute to the code and see where things are. I’d be happy to help!

Cheers

**Comment by Samreay** [comment]
Ah right, internal change only. Yeah, that sounds feasible.
