### ISSUE TITLE
Add installation instructions to the github.io page

### ISSUE THREAD

**Issue by tmcclintock** [Samreay/ChainConsumer#20]
Right now, the top google results for "chain consumer" with a space is the github.io page, and this repo isn't on the first page of google results. This is fine, but the installation instructions aren't on the github.io page. Either these should be added or a link back to the repo's installation instructions should be added to facilitate installation for someone making that search.

**Comment by Samreay** [comment]
Hi Tim,

I don't think I'm following you - the install instructions are located on the home page of the io documentation [here](https://samreay.github.io/ChainConsumer/index.html). Are you recommending they be put elsewhere as well?

**Comment by tmcclintock** [comment]
You are correct and I somehow missed that. My bad.

Also my name is Tom.

**Comment by Samreay** [comment]
Oops, my bad, sorry mate!
