### ISSUE TITLE
Cannot match 2D figures made by ChainConsumer and getdist

### ISSUE THREAD

**Issue by dparkins** [Samreay/ChainConsumer#22]
I cannot get the output from getdist and chainconsumer to match, even using the same cosmomc chains. I attach figures showing what I mean.
![plot_om_sig8](https://cloud.githubusercontent.com/assets/3622802/26236496/f58f169a-3cb3-11e7-82b8-cec77730b427.png)
[testkids_2D.pdf](https://github.com/Samreay/ChainConsumer/files/1013359/testkids_2D.pdf)
Cosmomc chains have a weight (multiplicity) and a likelihood. I include both of these in my 'add_chain' statement
`fig = ChainConsumer().add_chain(final,weights=final_weights,posterior=final_post,parameters=paramnames)`

Any suggestion what I might be doing wrong?

**Comment by Samreay** [comment]
Hi David,

Looking at the differences it seems like the difference is in the binning, with chainconsumer used wider bins than getdist. Id suggest increasing the number of bins (ie `bins=1.5`) and see if the contours line up better. 

How many samples do you have in the chain?

**Comment by Samreay** [comment]
Hi David,

Looking at the differences it seems like the difference is in the binning, with chainconsumer used wider bins than getdist. Id suggest increasing the number of bins (ie `bins=1.5`) and see if the contours line up better. 

How many samples do you have in the chain?

**Comment by Samreay** [comment]
Hi David,

Looking at the differences it seems like the difference is in the binning,
with chainconsumer used wider bins than getdist. Id suggest increasing the
number of bins (ie `bins=1.5`) and see if the contours line up better.

How many samples do you have in the chain?

**Comment by Samreay** [comment]
Following this up, one thing found by the DES team is that some other libraries plot 68% and 95% confidence as their contours, whilst chainconsumer defaults to plotting 1 and 2sigma contours (so 39% and 85% for a 2D Gaussian). You can turn this off with `sigma2d=False` in the config and should like up better.

See https://samreay.github.io/ChainConsumer/examples/customisations/plot_confidence_levels.html for examples.
