### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'gridspec_kw'

### ISSUE THREAD

**Issue by surgithub** [Samreay/ChainConsumer#27]
Hi, I am new to chainconsumer.  I have installed it successfully on my system. I get the following error while testing any example given on the chainconsumer website:
TypeError: __init__() got an unexpected keyword argument 'gridspec_kw'

How to rectify this error? 

Thanks.

**Comment by Samreay** [comment]
This seems like a maptlotlib error. Have you tried updating matplotlib and rerunning the examples?

**Comment by surgithub** [comment]
Yes. I tried your suggestion but it is still leading to the same error.

**Comment by surgithub** [comment]
I am able to get Table outputs. The error appears when I run any example of contour plot.

**Comment by Samreay** [comment]
What matplotlib version are you using?

**Comment by surgithub** [comment]
1.3.1

**Comment by Samreay** [comment]
Then you will need to update matplotlib, the current version is 2.0.2 and 1.3.x is old enough not to support gridspec

**Comment by surgithub** [comment]
Thanks!
