### ISSUE TITLE
Default font size too small for publication

### ISSUE THREAD

**Issue by dparkins** [Samreay/ChainConsumer#3]
I used chainconsumer to generate the figures for a recent publication (https://arxiv.org/abs/1607.01884), which was submitted to JCAP. The referee response included the following comments:

> 7) Figure-4; Axes labels are very small and the resolution of the figure needs to be improved.

And these comments were repeated for figures 5, 6 and 7. Though the figures look great on the screen, would it be possible to have a different set of defaults for printing quality figures?

**Comment by Samreay** [comment]
Attaching explanation given in person for posterity. The plot method (https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.ChainConsumer.plot) takes figsize, which can be "PAGE", "COLUMN", "GROW", or a 2-tuple for the size (same as matplotlib) like (6,6). That should let you control the size of the figure.
