### ISSUE TITLE
Contours always being drawn as Gaussian.

### ISSUE THREAD

**Issue by matthewkirby** [Samreay/ChainConsumer#34]
Unless I am missing something, to draw the contours you use (from plotter.py)
`levels = 1.0 - np.exp(-0.5 * self.parent.config["sigmas"] ** 2)`
This assumes that our model parameters are always Gaussian distributed.

To draw contours more generally, you need to find the level that contains the volume you are looking for. This can be done by gridding the height of the map from 0 to zmax and then summing the volume of each bin with height greater than the current grid value (zthresh). When zthresh is 0, you expect to recover 1 (if normalized to 1). When zthresh is zmax, you expect to recover 0. If we calculate the area over a grid of zthresh, we can then interpolate to find zthresh that contains the volume that we are looking for. 

I have attached an example file that does just this.
[draw_contours.txt](https://github.com/Samreay/ChainConsumer/files/1116377/draw_contours.txt)

**Comment by Samreay** [comment]
Hey Matthew, this is correct. I will try and include the generalisation of the code in the next release of chainconsumer!

**Comment by Samreay** [comment]
Hmm, I am not sure if this is an issue or not. Would be good to chat with you and Eduardo about this - atm the levels are declared using Gaussian sigma as a proxy, but that doesnt mean that said levels are calculated incorrectly using the `_convert_to_stdev` method, which itself comes from astroML (https://github.com/astroML/astroML/blob/master/astroML/plotting/mcmc.py#L4).
