### ISSUE TITLE
TypeError while plotting in a for loop

### ISSUE THREAD

**Issue by manodeep** [Samreay/ChainConsumer#36]
First of all - thanks for the excellent package! I just started using `ChainConsumer` - so I am probably doing unusual/naive.

```python
    c = ChainConsumer()
    for f, nburn, lbl in zip(chainfiles, burn_in_steps, chainlabel):
        chain = load_chain_data(f)
        chain_param_dist = chain[nburn:, 0:nparams]
        lnlike = chain[nburn:, nparams]

        # since we have flat priors, posterior \propto likelihood
        lnpost = lnlike
        c = c.add_chain(chain_param_dist, parameters=param_names,
                        posterior=lnpost, walkers=nwalkers,
                        name=lbl)
    for i, param_idx in enumerate(plot_param_combos):
        outfile = "{0}{1}.{2}".format(filebase, i, outputfiletype)
        params = [param_names[idx] for idx in param_idx]
        print("Generating plot for params names = {0}".format(params))
        c.configure(kde=[False] * nchains,
                    shade=[True] * nchains,
                    sigmas=[0, 1, 2, 3],
                    bar_shade=[True] * nchains,
                    plot_hists=[False] * nchains,
                    diagonal_tick_labels=False)
        c.plotter.plot(filename=outfile, figsize="column",
                       parameters=params)
        print("Generating plot for params names = {0}...done".format(params))
```

This results in the following:

    Generating plot for params names = ['$\\log M_{min}$', '$\\sigma_{\\log M}$']
    WARNING:chainconsumer.analysis:Parameter $\log M_{min}$ is not constrained
    WARNING:chainconsumer.analysis:Parameter $\sigma_{\log M}$ is not constrained
    Generating plot for params names = ['$\\log M_{min}$', '$\\sigma_{\\log M}$']...done
    Generating plot for params names = ['$\\log M_1$', '$\\alpha$']
    error occurred for key = max_ticks val = 5
    All keys = ['max_ticks', 'linestyles', 'kde', 'tick_font_size', 'colors', 'plot_hists', 'legend_color_text', 'plot_color_params', 'cloud', 'statistics', 'legend_kwargs', 'bar_shade', 'label_font_size', 'watermark_text_kwargs', 'usetex', 'contour_labels', 'legend_location', 'legend_artists', 'shade_alpha', 'num_cloud', 'spacing', 'linewidths', 'serif', 'cmaps', 'sigmas', 'sigma2d', 'shade', 'smooth', 'flip', 'summary', 'contour_label_font_size', 'color_params', 'diagonal_tick_labels', 'shade_gradient', 'bins']
    Traceback (most recent call last):
      File "xx.py", line 140, in <module>
        main()
      File "xx.py", line 134, in main
        diagonal_tick_labels=False)
      File "/Users/msinha/anaconda/lib/python2.7/site-packages/chainconsumer/chain.py", line 597, in configure
        assert len(val) >= num_chains, \
    TypeError: object of type 'int' has no len()

I added the following lines into `chain.py` to help debug (which results in the additional info output in the preceeding block):

```python

        for key in self.config.keys():
            val = self.config[key]
            try:
                assert len(val) >= num_chains, \
                    "Only have %d options for %s, but have %d chains!" % (len(val), key, num_chains)
            except:
                print("error occurred for key = {0} val = {1}".format(
                        key, val))
                print("All keys = {0}".format(self.config.keys()))
                raise
```
My read is that `max_ticks` is already defined and therefore does not pass the check. Might be good to add an additional boolean flag per key option that records whether or not the comparison with `nchains` test should run. 

Thanks again!

**Comment by Samreay** [comment]
Hi Manodeep,

Ah, whats happening is that ChainConsumer (atm) only allows configure to be called once (and after all chains are loaded in). It is the repeated calls to it that break it, so I would restructure the code such that each chainconsumer instance is only configured once.

Also, there is no need to pass in lists of the same option, single options will apply to all chains (ie `kde=[False] * nchains` is the same as `kde=False` , which is also the same as not specifying it because `kde=False` is the default behaviour).

**Comment by manodeep** [comment]
Sorry about the mis-leading with the `nchains` multiplication, I was trying to solve the assertion error. I hacked my way around the `TypeError` by checking if the `self.config` was an empty `dict`; and if so, creating a list of validated keys. That solved my issue - but I have no idea about the side-effects. 

I had the configure right after I called `ChainConsumer` (before loading the chians). However, then the config options did not seem to take effect; that's why I put the `configure` within the plotting loop. Just to be clear, if I only call `configure` after all chains are loaded and before the plotting loop - all should be good? 

Thanks again for the quick response.

**Comment by Samreay** [comment]
Ah right, that makes sense. As to resetting config to an empty dict, that should be fine so long as you also set the configured boolean flag to false.

But yeah, from the doco: "Please ensure that you call this method after adding all the relevant data to the chain consumer, as the consume changes configuration values depending on the supplied data."

Some things (like whether or not to shade by default, the opacity of the shaded contours, whether to switch colouring to rainbow, etc) are dependent on the number of chains loaded in, hence the stipulation to call configure (once), after all data has been loaded.

**Comment by manodeep** [comment]
Fantastic - thanks! Sorry I missed that one from the docs.

**Comment by Samreay** [comment]
No worries mate, glad its an easy fix!
