### ISSUE TITLE
covariance ellipses

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#40]
Any plans on adding simple covariance ellipses to the plots?

**Comment by Samreay** [comment]
Can you provide an example figure, Im not sure what you mean

**Comment by steven-murray** [comment]
![image](https://user-images.githubusercontent.com/1272030/31648663-98dcea3a-b341-11e7-8b95-d50442a350cd.png)

Something like this. The ellipses are just 1- and 2- sigma areas of the multivariate normal defined by the covariance of the data. Can be useful for checking how Gaussian the posterior is.

**Comment by Samreay** [comment]
Ah right. Yeah that could be useful, will try to find some time to add that
in.

**Comment by Samreay** [comment]
You might have guessed, am doing an issue clean up. There is an `add_covariance` method now, detailed here: https://samreay.github.io/ChainConsumer/examples/Basics/plot_covariance_and_marker.html that solves this issue (hopefully).
