### ISSUE TITLE
Request: add either axes or figure as an argument to the plotter functions

### ISSUE THREAD

**Issue by tmcclintock** [Samreay/ChainConsumer#41]
I was hoping to make a figure that had two subfigures, and in each subfigure it would have an output from ChainConsumer. However, matplotlib subfigures cannot be created from matplotlib figure objects. Thus, I am unable to do this with ChainConsumer, since it creates and returns a figure object to the user.

A straightforward (I think) fix would be to optionally take in a figure or axes from the user, clear it, then do the plotting, then return the figure to the user.

The call signature in this case would look like
```python
import matplotlib.pyplot as plt
import chainconsumer as cc

fig, ax = plt.subplots(1)

mean = [0.0, 4.0]
data = np.random.multivariate_normal(mean, [[1.0, 0.7], [0.7, 1.5]], size=100000)

c = ChainConsumer()
c.add_chain(data, parameters=["$x_1$", "$x_2$"])
c.plotter.plot(axis=ax, filename="example.png", figsize="column", truth=mean)
```
this way, ```ax``` can be a subplot, and we could use ChainConsumer figuers inside a ```pyplot.subplots()``` figure.

**Comment by Samreay** [comment]
Ah yeah, that would be useful certaintly. Ill add it to the list haha,
hopefully can get to it after the DES meeting which is consuming my life
right now!

**Comment by manodeep** [comment]
While this issue is a few years old, would still be a fairly useful feature to have. What's required to implement this?

**Comment by tmcclintock** [comment]
It appears that most of the work would involve reworking some of the [Plotter](https://github.com/Samreay/ChainConsumer/blob/master/chainconsumer/plotter.py) object. At present, it internally creates the figure and axes for each of the plotting routines (just ctrl-f for "subplots").

It would be straightforward to make those optional arguments in the function, and only a bit annoying to check that the extents of the incoming axes satisfy what is required in each routine.

**Comment by manodeep** [comment]
Thanks @tmcclintock. I am trying to minimize the amount of coding involved. I was thinking of adding in a `return_axes` keyword, disabled by default, that returns the used axes when requested explicitly. 

@Samreay Would such a design work?

**Comment by Samreay** [comment]
Manodeep, my main concern with the first comment is that it only works when you're trying to plot the contour of 2 parameters. What is the use case when people want 3 parameters? Or two with histograms? Does matplotlib allow axes to have sub-axes, so to speak?

Im not following how adding a return_axes keyword would help. Are you suggesting chainconsumer would return axes? It returns the figure already, from which you get the axes, so I feel like I have missed the point, can you elaborate?

**Comment by jacobseiler** [comment]
+1-ing for adding an `axis` keyword for plotting.

I have a Figure with multiple subplots and on each of those subplots I want to just tell ChainConsumer "Hey, only plot the contours on this specific axis, literally don't do anything else".

While I could use ChainConsumer to make multiple different figures and then stitch them together in post, it feels like a round-a-bout and hacky solution.

**Comment by manodeep** [comment]
@Samreay Realised that I never responded to your comment. 

I am not sure how to retrieve the axes from the figure object. Do you mind showing an example?

**Comment by Samreay** [comment]
@jacobseiler so maybe the best usecase is you pass in an axis (maybe to a different method) and say - plot the contour of these two parameters here please and thats all it does. That could work without too much hassle I think!

@manodeep I believe this should work `axes = fig.axes`

**Comment by manodeep** [comment]
@Samreay I have tried that in ipython. From what I recall, the ipython autocomplete implied that the `fig.axes` was not the same as what you would get from `plt.subplot`. For instance, can you confirm that `fig.axes` and `axes` are the same object in [this line](https://github.com/Samreay/ChainConsumer/blob/master/chainconsumer/plotter.py#L394)?

**Comment by jacobseiler** [comment]
@Samreay That sounds like the best option.  Since I don't do heavy statistical analysis or corner style plots or anything fancy, I honestly use ChainConsumer to just easily plot contours.

Having a method that literally just accepts an axis and plots 2-parmater contours on the axis, without touching any labels/ticks/resizing/etc, would be perfection.

**Comment by Samreay** [comment]
@jacobseiler Alright, I'll see if I can add that in over the next couple of days.

@manodeep They're not the same - axes would be a (nxn) list, fig.axes returns a flattened list. But inside the lists the references are the same. You can compare the id's to confirm with the below snippet:

```
import matplotlib.pyplot as plt
fig, axes = plt.subplots(2,2)
axes2 = fig.axes
print(axes)
print(axes2)
```

**Comment by manodeep** [comment]
@Samreay Many thanks!

**Comment by Samreay** [comment]
Check out the `plot_contour` method in v0.29.0

Example here: https://samreay.github.io/ChainConsumer/examples/customisations/plot_axis.html

Reopen if there are any issues :)
