### ISSUE TITLE
Make KDE faster - 2D FFT using good kernel for boundary conditions (following getdist?)

### ISSUE THREAD

**Issue by Samreay** [Samreay/ChainConsumer#45]

**Comment by tmcclintock** [comment]
Any idea what the slow line is at the moment? Is it [this one](https://github.com/Samreay/ChainConsumer/blob/master/chainconsumer/kde.py#L39) where the covariance of the data is made?

**Comment by Samreay** [comment]
Nah the cov is pretty quick. The issue is more algorithmic, a fast solution would be instead of throwing all the data into the KDE, to instead create a finely binned 2d histogram of the data and kde that. The main issue developing this I should be making a 2d histogram, taking the FFT, multiplying by a kernel which supports boundary conditions (do not have this yet, this is the issue), iFFT and bam, done.

Ive attempted it a few times, but struggle to understand section A of the GetDist notes: http://cosmologist.info/notes/GetDist.pdf

**Comment by xuod** [comment]
Hi, I ran into this issue and found the fastKDE package (https://bitbucket.org/lbl-cascade/fastkde), which performs KDE very quickly while implementing a state-of-the-art method to choose an optimal bandwidth (see reference papers on the package page).

I've created a branch on a fork (https://github.com/xuod/ChainConsumer/tree/fastkde) to do a quick-and-dirty implementation and it seems to be doing quite well. I ran the documentation example (https://samreay.github.io/ChainConsumer/examples/customisations/plot_kde_extents.html#sphx-glr-examples-customisations-plot-kde-extents-py) for comparison (I've added the true marginal distribution as dotted black lines). It seems to work pretty well. Should I submit a pull request? The dependence on this external package needs to be implemented in a clean way.
![image](https://user-images.githubusercontent.com/9870063/39247397-9881d8dc-4899-11e8-8fb3-7ab01072ec15.png)

**Comment by Samreay** [comment]
Heya Cyrille! This looks awesome, Ill happily accept a pull request! I actually used fastKDE for alternative work and have been meaning to bring it into the fold because I was so impressed, just havent had the time. 

So, thank you for the hard work, much appreciated! 

I am unfortunately taking a break from my PhD for a month or so starting tomorrow (what timing haha), and I don't think Ill have the time to review the changes and ensure we have doco/tests all updated in the few hours Ill be working tomorrow, so you might not hear from me until I get back, but then lets definitely get this incorporated! Ill definitely have time to read through the code and comment on it tomorrow in the pull request, so please open one :)

**Comment by xuod** [comment]
OK, cool, will do :)
