### ISSUE TITLE
Figure has label chopped off

### ISSUE THREAD

**Issue by tmcclintock** [Samreay/ChainConsumer#5]
The figure found [here](https://samreay.github.io/ChainConsumer/examples/customisations/plot_kde_extents.html#sphx-glr-examples-customisations-plot-kde-extents-py) has a label chopped off at the top. This is purely a cosmetic issue with the documentation.

**Comment by Samreay** [comment]
Ah, true. Ill make the figure padding larger in the next patch. Cheers mate

**Comment by tmcclintock** [comment]
This is still an issue for some example figures. The [one chain](https://samreay.github.io/ChainConsumer/examples/customisations/plot_one_chain.html#sphx-glr-examples-customisations-plot-one-chain-py) example (probably the most important one) has labels chopped off. Would it help if I went through the docs and found every messed up example?

**Comment by Samreay** [comment]
Hey Tom, thanks for bringing that up. Have modified that example, and will go through the others again later this arvy to see what else is being cut off. I wish sphinx-gallery would simply take the images as given and save me that stupid workaround in every single example, grr!
