### ISSUE TITLE
trace plot with multiple chains

### ISSUE THREAD

**Issue by steven-murray** [Samreay/ChainConsumer#51]
Hi Sam,

I reckon it would be useful, when multiple walkers are specified for the chain and plotting the traceplot, to overplot different walkers, something like the following:

![image](https://user-images.githubusercontent.com/1272030/33862585-770d099a-df1e-11e7-96a4-f6ebaf769d00.png)

Instead of plotting each walker's chain appended in one long line.

**Comment by Samreay** [comment]
How did this slip by me for like... two years. My bad. There's an option to split the walkers in chainconsumer where you can essentially cut up one long chain into multiple smaller chains for this purpose. See the `divide_chain` method in main class. Sorry for the unfathomably long wait time for a response!

**Comment by steven-murray** [comment]
nice!
