### ISSUE TITLE
ticks position plot_summary

### ISSUE THREAD

**Issue by MCostanzi** [Samreay/ChainConsumer#54]
Hi,
is there a way to control the ticks position when using plot_summary?
I've tried to increase "max_ticks" in "configure, but it does not seem to change anything.
Thanks a lot

Matteo

**Comment by Samreay** [comment]
Hey Matteo,

Yeah the max_ticks that matplotlib takes isnt an absolute, matplotlib merely takes it as a suggestion, which can be frustrating. For the DES cosmology plots where we wanted ticks in specific places (like -1), we took the returned figure, got its axes and then manually called `set_x_ticks` (or similar). As of yet, there is no functionality to specify the ticks manually in the configure method. 

The other option at the moment is to change the extents such that matplotlib gives better ticks. You can set extents for specific parameters when you invoke plot, something like `extents={"$w$": (-1.5, -0.5)}`. 

Hope that helps, Ill try to work in manual tick numbers into a future version when the DES SN analysis calms down and I get to breathe!

**Comment by MCostanzi** [comment]
I see, thanks a lot for the tips!
Btw, how should I cite chainconsumer in a paper?

**Comment by Samreay** [comment]
No worries, let me know how it goes and I'll close down the issue when it's
all working.

For citing, there is bibtex available on the documentation homepage at
https://samreay.github.io/ChainConsumer/ which should do the trick!
