### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by grburgess** [Samreay/ChainConsumer#55]
I need this package in conda for another package I'm working on. Is it possible to have this done here, or would you like for me to get it pushed to conda?

**Comment by Samreay** [comment]
Im not familiar with the process of getting a package part of conda, what is the process for pushing it to conda? Ill try and get it done asap as soon as I figure out how.

**Comment by grburgess** [comment]
I'm new to it as well. The only issue is that the Pypi link for the package is not working.

I've been following the instructions here: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by grburgess** [comment]
I think I have figured out how to do this during the travis builds. The way I would progress is by doing continuous releases. There would be a script run by travis that makes the package, builds and then distributes to a channel. Conda-forge wants iterative releases. 

Shall I take a stab at this?

**Comment by Samreay** [comment]
Sure thing! Ive updated the `.travis.yml` on master to both use conda, have `anaconda-client` and have a commented out `deploy` phase as well. I've raised an issue with the travis-ci team (https://github.com/travis-ci/travis-ci/issues/9303) about getting the PyPI deployment to work, and at the moment have commented out both the github release deployment and the PyPI deployment. Happy to bring in a PR if you have a script based deployment for conda similar to the one detailed at https://gist.github.com/yoavram/05a3c04ddcf317a517d5

**Comment by Samreay** [comment]
Heya, take a look at the current repo, spent some time screwing around with travis and conda, and hopefully have something working. `conda install -c samreay chainconsumer` should hopefully work now too.

**Comment by HerculesJack** [comment]
Hi, could you also add versions for matplotlib 3? It seems that the current ones all require matplotlib >1.6.0,<2.1.0.

**Comment by Samreay** [comment]
Hey mate,

Chainconsumer allows all matplotlib 3.0.0 or above, I'm currently using it
with the latest version. The versions defined in the setup.py are

"matplotlib>1.6.0,!=2.1.*,!=2.2.*"

Which allows matplotlib v3

**Comment by HerculesJack** [comment]
> 
> Hey mate, Chainconsumer allows all matplotlib 3.0.0 or above, I'm currently using it with the latest version. The versions defined in the setup.py are "matplotlib>1.6.0,!=2.1.*,!=2.2.*" Which allows matplotlib v3

Sorry but I was referring to the [conda version](https://anaconda.org/samreay/chainconsumer/files?version=0.30.0), which requires "matplotlib >1.6.0,<2.1.0". I think you can just modify some yaml file for conda?

**Comment by Samreay** [comment]
Ah good catch, I'll modify the meta.yml and re-release it tonight! Sorry for the confusion :)

**Comment by Samreay** [comment]
v0.30.1 has been released with updated dependencies, let me know if you have any issues, and thanks for pinging me about the conda release! :)

**Comment by HerculesJack** [comment]
> 
> 
> v0.30.1 has been released with updated dependencies, let me know if you have any issues, and thanks for pinging me about the conda release! :)

Sure, it works for me now. Thanks!
