### ISSUE TITLE
Errors with matplotlib 2.2.2

### ISSUE THREAD

**Issue by wagoner47** [Samreay/ChainConsumer#58]
I needed a newer version of matplotlib for something else I'm working on, but I noticed an issue when I try to plot my contours with matplotlib 2.2.2 installed. Plotting the walkers gives some errors about fonts, but still works, but when plotting chains, I get a few warnings about text positions and then a RunTimeError that says only "limping signaled error" (see full Traceback message below). If I switch back to matplotlib 2.0.2, I can get all of the plots from chain consumer, but I have an issue with another plot I'm making at the same time. Is there any way to get chain consumer working with newer versions of matplotlib?

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    239 
    240     if 'png' in formats:
--> 241         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    242     if 'retina' in formats or 'png2x' in formats:
    243         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    123 
    124     bytes_io = BytesIO()
--> 125     fig.canvas.print_figure(bytes_io, **kw)
    126     data = bytes_io.getvalue()
    127     if fmt == 'svg':

~/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2261                 orientation=orientation,
   2262                 bbox_inches_restore=_bbox_inches_restore,
-> 2263                 **kwargs)
   2264         finally:
   2265             if bbox_inches and restore_bbox:

~/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    526             with cbook.open_file_cm(filename_or_obj, "wb") as fh:
    527                 _png.write_png(renderer._renderer, fh,
--> 528                                self.figure.dpi, metadata=metadata)
    529         finally:
    530             renderer.dpi = original_dpi

RuntimeError: libpng signaled error
```

**Comment by Samreay** [comment]
Interesting, I haven't seen the `libpng signaled error` issue before - the current reason why Ive had to restrict the matplotlib version is [this issue](https://github.com/matplotlib/matplotlib/issues/6789), which was slated to be fixed both in the 2.0.2, 2.1.1 and 2.2 release but unfortunately hasn't yet been fixed.

I'll have a play with it today and see if I can find a work around.

**Comment by tilmantroester** [comment]
I get the same error on macOS with conda and matplotlib versions 2.2.2 and 2.2.3. I haven't tried 3.0.0 yet, because that version has a bug that messes up colorbars...

**Comment by Samreay** [comment]
Yeah Ive done some testing and it looks like the bug is fixed in 3.0.0, however 3.0.0 has its own issues. Very frustrating -_-

**Comment by rdzudzar** [comment]
Hi, I reached here after trying to find solution to the same error. Is there a way to go around, or only way is re-installing older version of matplotlib so it is compatible?

**Comment by Samreay** [comment]
Actually if you can upgrade to the 3.x.x version of matplotlib, they fixed
the error. Upgrade or downgrade is the only solution unfortunately.

**Comment by rdzudzar** [comment]
Thank you, it's working now with matplotlib version 3.0.3.
