### ISSUE TITLE
Add AIC

### ISSUE THREAD

**Issue by Samreay** [Samreay/ChainConsumer#6]

**Comment by robert-crittenden** [comment]
From the Liddle 2007 paper: 

Simple AIC: - 2 ln L + 2k 
where k is the number of degrees of freedom in your model.  This is the large sample (N) limit.  

More generally, it is 
Full AIC: - 2 ln L + 2k + 2k(k+1)/(N-k-1).

**Comment by Samreay** [comment]
Implemented in ChainConsumer v0.15.1
