### ISSUE TITLE
plot_walks() modifies passed truth dict

### ISSUE THREAD

**Issue by nweaverd** [Samreay/ChainConsumer#61]
I noticed that when I call `c.plotter.plot_walks(chains=0, parameters=mypars1, convolve=500, truth=truthdict)`, several values in my `truthdict` got changed to `None`, such that if I were to call it again, the `truth` lines are no longer displayed.

I fixed my local version by adding 
```
        ## copy truth so as to prevent modification trickling up
        if type(truth) == dict:
            truth = truth.copy()
        if type(truth) == list:
            truth = list(truth)
```
at the beginning of `plotter.plot_walks( )` definition.

**Comment by Samreay** [comment]
Sorry for the delay getting back to you, been on holidays! I'll figure out what is mutating the dict and stop it doing so as soon as I can, thanks mate!
