### ISSUE TITLE
Adding a marker at some set of parameter values on top of chain contour plots

### ISSUE THREAD

**Issue by jessmuir** [Samreay/ChainConsumer#67]
I'm interested in putting a scatter-plot type marker on top of my chain contours, in addition to the dotted lines showing the true cosmology values. As in, I'd effectively like to be able to pass in an additional set of truth values, but mark them with say, a star marker rather than the dashed lines. Is there a way to do this?

**Comment by Samreay** [comment]
Not at the moment, but Ill see if I can add something today for you!

**Comment by Samreay** [comment]
In the meantime, here is a good workaround for using a Chain as a proxy. Note you have to add at least two steps because I didn't cater for single step chains. I'll try and fix that today too.
```
import numpy as np
from chainconsumer import ChainConsumer

np.random.seed(0)
data = np.random.multivariate_normal([0.0, 4.0], [[1.0, 0.7], [0.7, 1.5]], size=1000000)

c = ChainConsumer()
c.add_chain(data, parameters=["$x_1$", "$x_2$"])

marker_data = np.array([[1.0, 3.0],[1.0, 3.0]])
c.add_chain(marker_data, posterior=np.array([0,1]), plot_contour=False, 
            plot_point=True, marker_size=170, marker_style="*", color="r", name="Marker!")
fig = c.plotter.plot(figsize="column", truth=[0.0, 4.0])
```

**Comment by Samreay** [comment]
Ahhhh I did not close this, oops! I added an `add_marker` method ages ago, detailed in this example here: https://samreay.github.io/ChainConsumer/examples/Basics/plot_covariance_and_marker.html

Sorry for not chasing the issue down!
