### ISSUE TITLE
Removing labels in plot_summary

### ISSUE THREAD

**Issue by matthewkirby** [Samreay/ChainConsumer#68]
Recently I wanted to make a figure to compare the 1d posteriors on a parameter for several different realizations of mock data for the same fiducial model. The plot_summary method provided an extremely convenient and nice looking way to do this. However, each chain had a label that was very generic (realization1, realization2, ...). Since I was only dealing with a single parameter, I had more figure real estate locked up in the labels than the figure. The only way that I could get rid of the chain names was to go into the code and take the line out. Setting the chain names as empty strings or None wasn't able to solve the problem either. Is there any way in a future version of the code to have an option to suppress chain names on a summary plot?

**Comment by Samreay** [comment]
Definitely possible to add. Let me see if I can get that soon asap

**Comment by Samreay** [comment]
There is now a `show_names` options in `plot_summary`, detailed here:

https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.plotter.Plotter.plot_summary

Available in v0.26.3, let me know if that is what you were looking for and I'll close this out.

**Comment by matthewkirby** [comment]
This is exactly what I was looking for! Thanks a lot!

**Comment by Samreay** [comment]
Fantastic!
