### ISSUE TITLE
xlim, ylim?

### ISSUE THREAD

**Issue by ta298** [Samreay/ChainConsumer#69]
Dear Sam,

Thank you so much for an excellent module and documentation. I am having trouble locating how to define xlim, ylim as one would for a matplotlib plot. Is that feature available at all with ChainConsumer?

Thank you very much!

**Comment by Samreay** [comment]
Heya Tonima!

Hopefully what you want is the `extents` keyword when invoking `plotter.plot`.

You can see an example of this in use here: https://samreay.github.io/ChainConsumer/examples/customisations/plot_kde_extents.html

Let me know if that's not what you were looking for and we can figure out something that works.

Cheers

**Comment by ta298** [comment]
Thank you very much!

Best,
Tonima

**Comment by ta298** [comment]
Hi Sam,

I am having a matplotlib incompatibility issue:

chainconsumer 0.26.3 has requirement matplotlib!=2.1.*,!=2.2.*,>1.6.0, but
you'll have matplotlib 2.2.3 which is incompatible.


I am having trouble creating the plots:


Traceback (most recent call last):

  File "min_cost_chainconsumer.py", line 66, in <module>

    fig =
c.plotter.plot(filename="chain_consumer_neural_network_0p1_loglikelihood.pdf")#,

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/chainconsumer/plotter.py",
line 279, in plot

    self._save_fig(fig, f, dpi)

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/chainconsumer/plotter.py",
line 286, in _save_fig

    fig.savefig(filename, bbox_inches="tight", dpi=dpi, transparent=True,
pad_inches=0.05)

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",
line 2062, in savefig

    self.canvas.print_figure(fname, **kwargs)

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py",
line 2263, in print_figure

    **kwargs)

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py",
line 2573, in print_pdf

    self.figure.set_dpi(72)            # there are 72 pdf points to an inch

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",
line 985, in set_dpi

    self.dpi = val

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",
line 485, in _set_dpi

    self.set_size_inches(w, h, forward=forward)

  File
"/home/fas/urry/ta298/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",
line 909, in set_size_inches

    '({}, {})'.format(w, h))

ValueError: figure size must be finite not (nan, nan)


Is there a  workaround to deal with this?


Thank you so much!


Best,

Tonima

**Comment by Samreay** [comment]
Heya, have you tried running

`pip install -U matplotlib`

The 2.2.* versions are incompatible because matplotlib added a bug, but its fixed in the 3.* versions.

**Comment by ta298** [comment]
Thanks again! It took some time to update everything but it seems to be
working well now!

Best,
Tonima

**Comment by Samreay** [comment]
Glad it worked!

**Comment by arthurmloureiro** [comment]
Hi @Samreay !

I wonder if there is still an option to set the xlim, ylim or the extends somehow without having to use the custom axis ?
