### ISSUE TITLE
customizing label size for color bar

### ISSUE THREAD

**Issue by Yucheng-Zhang** [Samreay/ChainConsumer#73]
Hi,

The label size for color bar is fixed to 14 in the code (https://github.com/Samreay/ChainConsumer/blob/master/chainconsumer/plotter.py#L216). Maybe it's better to make it customizable?

Thanks!

**Comment by Samreay** [comment]
Good catch, it should be linked to the other label sizes, I'll try the update soon! In the meantime whilst I code things up, I'd recommend using figsize to change the apparent size of the label 🙂

**Comment by Samreay** [comment]
Oops, I forgot to follow this up! This should now be implemented in v0.31.0 using the normal label font size option :)

**Comment by Yucheng-Zhang** [comment]
Yes, I noticed that so I closed the issue. Thanks!
