### ISSUE TITLE
Adding prior distribution to corner plots

### ISSUE THREAD

**Issue by sharanbngr** [Samreay/ChainConsumer#74]
I was wondering if there is a good way to overlay prior distributions to the plots. I have tried to add the prior chain as a separate chain as shown in this example but then all the subplot axes reset to cover the entire prior space while I still want to zoom into the region where the posterior peaks. 

https://samreay.github.io/ChainConsumer/examples/Basics/plot_two_disjoint_chains.html#sphx-glr-examples-basics-plot-two-disjoint-chains-py

**Comment by Samreay** [comment]
Heya! You can specify custom extents to keep it all nice and zoomed in: see
this example here:

https://samreay.github.io/ChainConsumer/examples/customisations/plot_kde_extents.html#sphx-glr-examples-customisations-plot-kde-extents-py

**Comment by sharanbngr** [comment]
@Samreay Thank you, that along with the summary statistics has helped

**Comment by Chris-Pedersen** [comment]
Hi @Samreay , I am attempting to do something similar, and I am trying to get only the prior distribution to be plot on the 1D histograms but not the 2D contours. I can't find any syntax to do this, or to set the alpha on the 2D contour to be 0. Is there a way to change the line colours and styles on the 2D contours separately, or plot only the 1D values?

Thanks!

**Comment by Samreay** [comment]
If you only want the marginalised distributions, check out `plot_distributions` rather than the generic `plot` command :)

**Comment by Chris-Pedersen** [comment]
Thanks for the tip, is there a way to do this on top of the corner plot? I'm attempting to get a triangle plot with the prior distribution for each parameter on the 1D distributions only. I think `plot_distributions` will only give me the 1D distributions on their own.

**Comment by Samreay** [comment]
You can only turn the shading off at the moment, the line width and colour
are linked between the 2D and 1D distributions at the moment. Ill try and
add an option tomorrow to allow for some control there. a hide_contour
option when loading the chains in might be easiest.

**Comment by Chris-Pedersen** [comment]
That would be amazing, thanks!

**Comment by Samreay** [comment]
Alrighty, this should now be possible in v0.31.1. See the example here for details: https://samreay.github.io/ChainConsumer/examples/customisations/plot_as_prior.html

If there are any issues, please let me know, and once youve verified it works, feel free to close out the issue :)

**Comment by Chris-Pedersen** [comment]
Thanks a lot for this really appreciate it! I'll check on Monday and update

**Comment by Chris-Pedersen** [comment]
Super this works perfectly, thanks again! (I can't close the issue as I wasn't the OP)

**Comment by Samreay** [comment]
No worries, glad its useful!
