### ISSUE TITLE
Feature request: HDF5 support for loading chains

### ISSUE THREAD

**Issue by privong** [Samreay/ChainConsumer#76]
One of the commonly used MCMC tools in astrophysics, `emcee`, has added support for saving chains in HDF5 files (https://emcee.readthedocs.io/en/stable/user/backends/#emcee.backends.HDFBackend). Would it be possible to add support for it to ChainConsumer? I'm not aware if there's a "standard" structure for storing MCMC chains in HDF5 files, but the `emcee` structure seems fairly straight-forward.

I believe implementing this would only add the (optional?) `h5py` module dependency.

**Comment by Samreay** [comment]
Fixed in https://github.com/Samreay/ChainConsumer/pull/103
