### ISSUE TITLE
Scientific notation for axes ticks is not working with usetex=True

### ISSUE THREAD

**Issue by bvgoncharov** [Samreay/ChainConsumer#78]
Hi!

I would like to report a bug and a possible solution.
I noticed that when, by default, `usetex=True`, I get this error when I try to make a corner plot:
```
RuntimeError: latex was not able to process the following string:
b'$\\\\times\\\\mathdefault{10^{4}}\\\\mathdefault{}$'
```
The problem happens spontaneously for some of my results, where I plot MJD, which is a large number in units of days (i.e., ~ 57000).

I found two ways to fix the problem:

1. Do `usetex=False`
2. Hardcode `ax.ticklabel_format(useOffset=False, style='plain')` for all "axes"/"ax" objects in plotter.py.

If that may be a common problem, I would suggest the most simple solution: to hardcode (2) on the main branch. I also see more advanced solutions:

 - to automatically switch off scientific notation when `usetex=True`
 - fix the latex string that is passed to the latex interpreter

**Comment by Samreay** [comment]
Hey Boris! You would not believe how many issues LaTeX has caused me over the years, I can now add another to the file! Do you have the raw text you inputted that I can see? Does it contain the mathdefault strings or is that something added by matplotlib?

**Comment by bvgoncharov** [comment]
Hi Sam! 

Thanks for your reply.
Yes, your second question describes what caused the problem. My raw text for labels worked well. It looks like it is only the scientific notation that caused an error: 
```b'$\\\\times\\\\mathdefault{10^{4}}\\\\mathdefault{}$'```

The latex compiler did not like something in that string above.

**Comment by Samreay** [comment]
How odd, something funky is going on with matplotlib adding "mathdefault" to the labels. I'll root around on the forums and see if this is a new change. Can I ask what version of matplotlib you are using, and if its not the latest version, does the error still persist if you update matplotlib?

**Comment by bvgoncharov** [comment]
I was using Python 3 with version 3.1.2 of matplotlib.
After I updated matplotlib to 3.2.1, I still get the same error, unless I switch off the scientific notation manually.

**Comment by Samreay** [comment]
Hey Boris, I'm unable to replicate this on my end, but a search of the forums shows that its an occasional issue when python+matplotlib+latex versions misalign.

Can I ask you to try adding this above your plot and let me know if it fixes your problem? Hard for me to know yes or no without being able to get the error initially!

```
from matplotlib import rcParams
rcParams['text.latex.preamble'] = r'\newcommand{\mathdefault}[1][]{}'
```

**Comment by bvgoncharov** [comment]
Hi Sam, it looks like the two lines you recommended fix the problem too.
