### ISSUE TITLE
How to get 95% (or any N%) error level on a parameter from the sample?

### ISSUE THREAD

**Issue by deltasata** [Samreay/ChainConsumer#79]
Suppose, from the fit, I have a sample of two parameters: A and B. I want the mode and 95% confidence levels of 1-D histogram/PDF of both A and B.  
Setting `
>configure(statistics='max',summary_area=0.95)

gives me the values on the plot using "plotter.plot()".

 However, I want the values in the code itself. Is there a way of getting the values?

**Comment by Samreay** [comment]
Yup! You can use the analysis class to get the summaries themselves as a series of three values - the lower bound, middle point, and upper bound: https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.analysis.Analysis.get_summary

If you want the 95% CL instead of 68%, you can pass summary_area=0.95 to configure as specified here beforehand: https://samreay.github.io/ChainConsumer/chain_api.html#chainconsumer.ChainConsumer.configure

Hope that helps!

**Comment by deltasata** [comment]
Thanks a lot for the quick help.
Yes, I am trying this, but getting the error:
>TypeError: get_summary() missing 1 required positional argument: 'self'
in the code
>chainconsumer.analysis.Analysis.get_summary( chains=postsamples,parameters=["$\mu$", "$\Delta t$"])

How to use chainconsumer.analysis.Analysis.get_summary) ?

**Comment by Samreay** [comment]
It should work if you just remove the second .Analysis from your call, as
you are currently accessing the class level method and not the instance
method:


chainconsumer.analysis.get_summary( chains=postsamples,parameters=["$\mu$",
"$\Delta t$"])

**Comment by deltasata** [comment]
No it says
>AttributeError: module 'chainconsumer.analysis' has no attribute 'get_summary'

**Comment by deltasata** [comment]
Could you please post a minimal working example/code?

**Comment by deltasata** [comment]
Got it. With some trail and error I found that I had to use:
>c = ChainConsumer()
    c.add_chain(postsamples, parameters=["$\mu$", "$\Delta t$"])
    c.analysis.get_summary()

**Comment by Samreay** [comment]
Yup, you need to initialise the object first. In case there are other things you need to do in the future, I'll point out the examples in the documentation have dozens of working code examples: https://samreay.github.io/ChainConsumer/examples/plot_table.html
