### ISSUE TITLE
Add DIC

### ISSUE THREAD

**Issue by Samreay** [Samreay/ChainConsumer#8]
Paper by Andrew Little 2009 comparing AIC, BIC, DIC

0903.4210

Also

https://arxiv.org/abs/astro-ph/0701113

**Comment by robert-crittenden** [comment]
2007 MNRAS paper by Andrew Liddle: Mon. Not. R. Astron. Soc. 377, L74–L78 (2007)

defines all these information criteria

**Comment by robert-crittenden** [comment]
Divergence information criterion (DIC): 

Must evaluate: 
 bar{theta}, which is the expectation of the parameters over the posterior. 
 chisq (bar{theta}), the value of chi-squared at this mean parameter. 
 bar(chisq (theta)), the average chi-squared (expectation value) over the posterior 

If I understand right, 
DIC: 2* bar(chisq(theta)) - chisq (bar{theta}).  
up to a constant that seems to depend on the data, so would not affect comparisons between models.

**Comment by Samreay** [comment]
Implemented in ChainConsumer v0.15.1
