### ISSUE TITLE
Errobars to markers

### ISSUE THREAD

**Issue by mdzrod** [Samreay/ChainConsumer#80]
I have a 2 parameter contour and I would like to plot a data point (with its uncertainty in the horizontal direction). I see that I can use add_marker to plot the data point, however I do not see how I can add an error bar to that point. Is there a way I can achieve this??

**Comment by Samreay** [comment]
Hey Mariangelly, alas theres no easy way to specify markers in that much detail, however what I would do is simple emulate a chain. If you have some mean and std, you might as well create a fake chain by sampling a million points from a normal with the right mean and std?

**Comment by mdzrod** [comment]
Thank you for your prompt response. Unfortunately, I don't think that will work for what I want to do. Each “plot” is an axis object, right?  How can one extract the axis objects? 

Currently I only have a 2 parameter plot, so one contour plot with its two histograms. Not sure how I can extract the position of the main axis.

**Comment by Samreay** [comment]
Well if you have a figure you can call get_axes or similar to get the axes, but thats not what I was getting at, I was suggesting just adding a chain you make on the spot using add_chain, something like:

```
c = ChainConsumer()
c.add_chain(chain, name="Your actual MCMC chain")
c.add_chain(random.rvs(loc=mean, scale=uncert, size=(1000000,1)), name="The fake point with uncertainty")
```

**Comment by mdzrod** [comment]
I'm assuming that makes a contour right?

I couldn't find random.rvs ...

**Comment by Samreay** [comment]
If its only in 1D it wont make a contour, it will just show it in the marginalised distributions.

And apologies, I meant `normal.rvs` from `scipy.stats.normal`
