### ISSUE TITLE
Conda install 2.0

### ISSUE THREAD

**Issue by skilllessaustin** [Samreay/ChainConsumer#81]
Greetings
Sometime ago there was a similar issue on installing the package with conda
I've been working for almost a year with chainconsumer installed with conda using the following commend "conda install -c samreay chainconsumer" and everything was fine until last days when I decided to completely reinstall Anaconda
After the reinstallation I had to reinstall all the packages needed for my projects, one of which is chainconsumer. I tried to use the same command line for installation, but for some reason it doesn't work. Here is what I got after trying to use the command line:

----------------------
$ conda install -c samreay chainconsumer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - chainconsumer -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

-------------------

As far as I see it it looks like chainconsumer can not be installed on Python 3.8 for some reason, but I can be wrong. Could you please help me with this problem?

**Comment by Samreay** [comment]
Looking into this now, will try and have a py3.8 build out on conda asap. In the meantime, pip installing will hopefully work, but I'll update this issue when I have something out on conda as well. Cheers

**Comment by Samreay** [comment]
Hmm, Ive added a python 3.8 build to the conda release but it doesnt actually get made. I wonder if there are delays putting py3.8 in the conda-build ecosystem thats holding it up (see https://github.com/conda/conda-build/issues/3835) or if I've done something incorrect. Ill keep digging, but `pip install chainconsumer` should work in the interim

**Comment by skilllessaustin** [comment]
Thank you a lot for quick reply. I've tried pip installing to base environment and it worked fine. 

I also tried to install chainconsumer manually by downloading .tar.bz2 files - it did not work either.
I hope you can figure it out how to fix it)
Thanks a lot again
