### ISSUE TITLE
Documentation site 404

### ISSUE THREAD

**Issue by Chris-Pedersen** [Samreay/ChainConsumer#82]
Hi @Samreay , I noticed that the documentation site https://samreay.github.io/ChainConsumer/ is down, just a heads up. Hope everything is ok!

**Comment by Samreay** [comment]
Oh no! Thanks for the heads up, let me jump on this right now!

**Comment by Samreay** [comment]
Turns out this was a github issue I believe. I could access the documentation if I just put an index.html at the end of the URL, and after forcing the doco to regenerate and waiting an hour or two, the page appears back (thankfully). Figners crossed it stays up this time!
