### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by humnaawan** [Samreay/ChainConsumer#88]
Hello,

I have been trying to install `chainconsumer` on a cluster and it's been so much more painful than I was hoping for. Doing a pip install presumably successfully installs the package but when I try to run it, I get an error saying `RuntimeError: Failed to process string with tex because latex could not be found` arising from line 283 in "chainconsumer/plotter.py" (`fig.canvas.draw()`).

I tried installing latex (via pip install) but that didn't fix the problem. I then tried to just install `dvipng` as suggested in the readme but that has been utterly unsuccessful given that I do not have sudo privileges on the cluster - and after hours of figuring out the config issues, I think I need to install `libgd` from source before I can install `chainconsumer` but that seems like another rabbit hole.

Given my frustration with installation from source, I then tried installing `chainconsumer` via conda in the hopes that all the dependencies would be taken care of, but no, I get the following error:
```
> conda install -c samreay chainconsumer

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                       

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - chainconsumer -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0

Your installed version is: 2.17
```

I tried running the conda install in a new environment without any other packages installed and it works, but only if I don't specify the python version.

After testing out some of the variants of the order of packages in a new environment, it seems like the conda install fails when I specify python=3.8 (in hindsight, that is what the conda conflict report above was saying). Is there a reason why one cannot one of the latest versions of python (I was using  3.8.12)? If this is indeed a requirement, it should be specified explicitly somewhere.

Once I downgraded to python 3.7, at least the conda install worked but even then, when I tried to run the code, I get the same error as before (`RuntimeError: Failed to process string with tex because latex could not be found`), even after I explicitly install latex. I do not understand how conda install could be successful without handling all the dependencies.

I realize I could use `chainconsumer` as an afterburner and process the chains on my local computer where I am able to run things but it's serious a hassle to have to use two different machines. It seems though this is my only option right now since I am out of ideas that don't require unspecified amounts of time. It would be nice if someone could fix whatever is causing these problems. Thank you!

**Comment by Samreay** [comment]
Hey mate, this is actually a pretty common issue. Many clusters have limited to no support for rasterisation of graphics, and I know a lot of users simply save the chains out and then analayse them off the cluster because of this. Sometimes though, the clusters might have a latex module you can enable (its not pip installable), or you could try and ask matplotlib to not invoke latex, which you can do by passing in 

`c.configure(usetex=False, serif=False)`

This isn't always guaranteed to work though (because Chainconsumer ultimately doesn't control what matplotlib decides to load in), but give that a shot just on the pip install for chainconsumer.

**Comment by humnaawan** [comment]
thank you - using `usetex=False` works (with the pip-installed version of the package)! it might be worth adding this to the readme where the `dvipng` issue is mentioned.

also, i did try to use `serif=False` but nothing would change and i didn't think to try toggling `usetex` - if it is indeed true that these two depend on each other, it may be worth adding that to the documentation for `configure`.

i'll leave the issue open in case either changes above need to be tagged here before closing the issue, but feel free to close it.

**Comment by Samreay** [comment]
Have updated the readme to include this explicitly to help anyone in the future with the same problem :) Thanks Humna!
