### ISSUE TITLE
Conda install for python 3.9

### ISSUE THREAD

**Issue by MrBudgens** [Samreay/ChainConsumer#90]
At present, conda installation fails because of the requirement: python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Please can you make a 3.9 version available? In the meantime I will use pip to install it

**Comment by Samreay** [comment]
Hmm Im considering simply removing it from conda. I put it up there when it was requested, but I have no binaries that I need to build, and so the whole point about having rebuilt wheels for different python versions and operating systems is a bit pointless for this repo.
