### ISSUE TITLE
Plotting color scatter plot without contours

### ISSUE THREAD

**Issue by Jasonpoh** [Samreay/ChainConsumer#91]
Hi, I'm trying to plot multiple color scatter plots without the contours (I do not have enough points to create accurate contours, so I just want to see the distribution of points with respect to different parameters). 

I've tried following the template here: https://samreay.github.io/ChainConsumer/examples/more/plot_colorpoints2.html#sphx-glr-examples-more-plot-colorpoints2-py

But following that code but adding a "plot_contour=False" argument to c.configure removes not just the contours but the point clouds as well. Is there a way to just plot the point clouds?

**Comment by Samreay** [comment]
Going to ensure this is an example in the 1.0.0 documentation
