### ISSUE TITLE
Bad parameter label visualization and 1D contours not matching 2D ones

### ISSUE THREAD

**Issue by davidepelliciari** [Samreay/ChainConsumer#93]
Hi all,
I'm using ChainConsumer for a while and sometimes the label of some parameters are poorly displayed, like in this following case for the D parameter. What is going on here and how can I fix it? In this example the truth value for D is 3.5838589, so I'm not understanding why of this bad visualization.

![image](https://user-images.githubusercontent.com/62055692/175294949-52cd4e01-adc0-448e-b9ca-25cbe28706eb.png)

Also, if you look to the 1D marginalised posterior distributions, you'll notice that the interior darker regions are not matching the same regions in 2D posterior distributions. I tried some combinations for the following 3 parameters:

`sigma2d`, `sigmas` and `summary_area`

but I didn't manage to obtain the desired result..

Thank you in advance,

Davide

**Comment by Samreay** [comment]
Sorry for only just seeing this, turns out I accidentally unsubscribed from my entire project, not just a single issue -_-

I'm going to close this and older issues but still try and address in an upcoming refactor
