### ISSUE TITLE
Mathtex parsing bugs

### ISSUE THREAD

**Issue by LouisDesdoigts** [Samreay/ChainConsumer#94]
So I've been encountering some odd behavior when using both `plotter.plot()` and `plotter.plot_summary()` and mathex rendering.

Minimal example:
```python
import numpy as np
from chainconsumer import ChainConsumer

data = np.random.normal(0, 1, (10000,))
c = ChainConsumer().add_chain(data, parameters=["$\alpha$"])
fig = c.plotter.plot()
```

The full stack-trace is very large so here is the top error, which causes two other exception to be raised.

```python
---------------------------------------------------------------------------
ParseException                            Traceback (most recent call last)
File ~/mambaforge/envs/dlux/lib/python3.10/site-packages/matplotlib/_mathtext.py:1983, in Parser.parse(self, s, fonts_object, fontsize, dpi)
   1982 try:
-> 1983     result = self._expression.parseString(s)
   1984 except ParseBaseException as err:

File ~/mambaforge/envs/dlux/lib/python3.10/site-packages/pyparsing/core.py:1141, in ParserElement.parse_string(self, instring, parse_all, parseAll)
   1139     else:
   1140         # catch and re-raise exception from here, clearing out pyparsing internal stack trace
-> 1141         raise exc.with_traceback(None)
   1142 else:

ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)

The above exception was the direct cause of the following exception:
```

However, oddly if we use `\phi` instead of `\alpha`, we do not get an error, ie:

```python
import numpy as np
from chainconsumer import ChainConsumer

data = np.random.normal(0, 1, (10000,))
c = ChainConsumer().add_chain(data, parameters=["$\phi$"])
fig = c.plotter.plot()
```

In my testing this error also occurs (both for `\phi` and `\alpha`) with the `plotter.plot_summary()` method. This is using version '0.34.0'. Any help is greatly appreciated!

Cheers

**Comment by Samreay** [comment]
Sorry for only just seeing this, turns out I accidentally unsubscribed from my entire project, not just a single issue -_-

I'll see if I can reproduce it, my initial thought with any string with backslash in it is to just stick a `r` at the front of the string and confirm its still an issue
