### ISSUE TITLE
Feature request : Option to parse a custom fig instance

### ISSUE THREAD

**Issue by Uddiptaatwork** [Samreay/ChainConsumer#95]
In accordance with the reasons below:
- Comparison plots
- Custom matplotlib rcparams/style for scientific publications

Could the option to have a custom fig instance as an argument to the plotter be added?
Something like :
` fig1,axs1 = plt.subplots(3,3,);  c.plotter.plot(fig=fig1)`

I want to make a corner plot with a custom figure instance. This feature would be extremely helpful.

**Comment by Samreay** [comment]
Sorry for only just seeing this, turns out I accidentally unsubscribed from my entire project, not just a single issue -_-

Ill add this to the list of features we want to add for a new version

**Comment by Samreay** [comment]
Using a custom figure is difficult due to the axes and additional figure layout in creation. But adding to the 1.0.0 milestone to ensure there are examples with how to use external axes.
