### ISSUE TITLE
Title bug when `display=True`

### ISSUE THREAD

**Issue by homerjed** [Samreay/ChainConsumer#98]
Hi - thanks for the great package!

I have a little bug that may be of interest.

When I run this little plot
```
def plot_data():
    datas = [
        np.random.normal(size=(10000, 2)) 
        for _ in range(3)]
    c = ChainConsumer()
    for data in datas:
        c.add_chain(data, name="x")
    c.configure(bar_shade=True)
    fig = c.plotter.plot(display=True)
    fig.suptitle("title")
    plt.show()

plot_data()
```

and set `display=True` the title disappears from the plot. I am not sure if this is intentional. 

Cheers

**Comment by Samreay** [comment]
Huh. That is not intentional. And sorry for only just seeing this, turns out I accidentally unsubscribed from my entire project, not just a single issue -_-

Will look into it!

**Comment by Samreay** [comment]
Have actually removed the display functionality in v1.0.0, with it returning a figure now and you can then run `fig.show()` which should hopefully show the title. If not, someones going to have to knock matplotlib over the head again!
